-- Seed: portfolio page content (hero, impact stats, industries, case studies, testimonial)
-- Transcribed verbatim from src/app/pages/portfolio/portfolio.component.ts

-- Hero
insert into page_heroes (page, badge, title, subtitle, cta_primary_label, cta_primary_link, cta_secondary_label, cta_secondary_link, tech_badges, code_snippet)
values (
  'portfolio',
  $txt$🏆 8+ Years of Enterprise Development Experience$txt$,
  $txt$Case Studies & Representative Work$txt$,
  $txt$The following case studies illustrate the types of solutions, challenges, and results our expertise can deliver. They represent the scope and quality of work we bring to every engagement.$txt$,
  null,
  null,
  null,
  null,
  null,
  null
)
on conflict (page) do update set
  badge = excluded.badge,
  title = excluded.title,
  subtitle = excluded.subtitle,
  cta_primary_label = excluded.cta_primary_label,
  cta_primary_link = excluded.cta_primary_link,
  cta_secondary_label = excluded.cta_secondary_label,
  cta_secondary_link = excluded.cta_secondary_link,
  tech_badges = excluded.tech_badges,
  code_snippet = excluded.code_snippet;

-- Impact stats (section: impact)
delete from stat_blocks where page = 'portfolio' and section = 'impact';
insert into stat_blocks (page, section, icon, value, label, description, sort_order) values
('portfolio', 'impact', '🚀', '50+', 'Projects Delivered', 'Successfully completed enterprise projects', 1),
('portfolio', 'impact', '📈', '3x', 'Performance Gain', 'Average improvement in system performance', 2),
('portfolio', 'impact', '💰', '40%', 'Cost Reduction', 'Average savings in operational costs', 3),
('portfolio', 'impact', '⭐', '4.9/5', 'Client Rating', 'Average satisfaction score', 4);

-- Industries
truncate table industries restart identity cascade;
insert into industries (icon, name, description, sort_order) values
('🛍️', 'E-Commerce & Retail', 'Online stores and retail platforms', 1),
('💼', 'Financial Services', 'Banks, insurance, and fintech', 2),
('🏥', 'Healthcare', 'Medical systems and health tech', 3),
('🏭', 'Manufacturing', 'Industrial automation and IoT', 4),
('📦', 'Logistics', 'Supply chain and delivery systems', 5),
('🎓', 'Education', 'E-learning and EdTech platforms', 6);

-- Case studies (37 items)
truncate table case_studies restart identity cascade;
insert into case_studies (title, company, industry, icon, project_type, duration, team, challenge, solution, results, technologies, sort_order) values
(
  'E-Commerce Platform Modernization',
  'Fortune 500 Retail Company',
  'Retail & E-Commerce',
  '🛍️',
  'Platform Modernization',
  '8 months',
  '4 developers',
  $txt$Legacy monolithic e-commerce platform causing slow deployments, scaling issues during peak seasons, and poor mobile experience leading to 35% cart abandonment.$txt$,
  $txt$Implemented microservices architecture with Angular PWA frontend, Node.js backend, and Azure cloud infrastructure. Introduced CI/CD pipelines, containerization with Kubernetes, and implemented a headless commerce approach.$txt$,
  $json$[{"metric":"300%","description":"Faster page load times"},{"metric":"10x","description":"Peak traffic capacity"},{"metric":"50%","description":"Reduced cart abandonment"},{"metric":"$2M","description":"Annual savings"}]$json$::jsonb,
  array['Angular','Node.js','Docker','Kubernetes','Azure','PostgreSQL','Redis'],
  1
),
(
  'Enterprise CRM System Integration',
  'B2B SaaS Company',
  'Technology',
  '📊',
  'System Integration',
  '6 months',
  '3 developers',
  $txt$Multiple disconnected systems causing data silos, hours of manual data entry, and limited real-time reporting capabilities affecting sales team productivity.$txt$,
  $txt$Built unified API layer with .NET Core, created real-time Power BI dashboards, and implemented automated workflows with Azure Logic Apps to integrate 5 disparate systems.$txt$,
  $json$[{"metric":"75%","description":"Less manual data entry"},{"metric":"Real-time","description":"Cross-system sync"},{"metric":"60%","description":"Faster reporting"},{"metric":"$1.5M","description":"Revenue increase"}]$json$::jsonb,
  array['.NET Core','Angular','SQL Server','Azure Service Bus','Power BI','Azure Logic Apps'],
  2
),
(
  'Legacy System Modernization',
  'Insurance Industry Leader',
  'Insurance & Finance',
  '🏢',
  'Digital Transformation',
  '18 months',
  '6 developers',
  $txt$20-year-old mainframe system with $500K annual licensing costs, difficulty hiring specialized talent, and 6-month feature deployment cycles limiting market competitiveness.$txt$,
  $txt$Systematically migrated monolithic COBOL application to .NET microservices with Angular frontend using strangler fig pattern, maintaining zero downtime throughout migration.$txt$,
  $json$[{"metric":"$5M","description":"3-year savings"},{"metric":"40x","description":"Faster deployments"},{"metric":"200+","description":"Dev talent pool access"},{"metric":"99.99%","description":"System uptime"}]$json$::jsonb,
  array['.NET Core','Angular','Azure','Docker','PostgreSQL','Event Sourcing','Kafka'],
  3
),
(
  'Real-Time Analytics Platform',
  'Financial Services Company',
  'Financial Services',
  '📈',
  'Data Platform',
  '10 months',
  '5 developers',
  $txt$Batch-based analytics system with 24-hour data lag causing delayed business insights, missed trading opportunities, and inability to detect fraud in real-time.$txt$,
  $txt$Built real-time streaming data pipeline with Apache Kafka, created interactive Angular dashboards, implemented ML-powered anomaly detection, and deployed on AWS for global scale.$txt$,
  $json$[{"metric":"100x","description":"Faster data processing"},{"metric":"Real-time","description":"Fraud detection"},{"metric":"$800K","description":"Infrastructure savings"},{"metric":"30%","description":"Revenue increase"}]$json$::jsonb,
  array['Node.js','Angular','Apache Kafka','Elasticsearch','AWS','Python','TensorFlow'],
  4
),
(
  'Healthcare Patient Portal',
  'Regional Hospital Network',
  'Healthcare',
  '🏥',
  'Patient Experience',
  '12 months',
  '5 developers',
  $txt$Fragmented patient experience with separate portals for appointments, records, and billing. Low patient engagement and high call center volumes for routine inquiries.$txt$,
  $txt$Built unified HIPAA-compliant patient portal with Angular frontend, secure .NET backend, integrated with Epic EHR via FHIR APIs, and added telehealth capabilities.$txt$,
  $json$[{"metric":"85%","description":"Patient adoption rate"},{"metric":"60%","description":"Fewer call center calls"},{"metric":"4.8/5","description":"Patient satisfaction"},{"metric":"50%","description":"Faster appointment booking"}]$json$::jsonb,
  array['Angular','.NET Core','Azure','FHIR APIs','Epic Integration','SQL Server','WebRTC'],
  5
),
(
  'Supply Chain Optimization',
  'Global Manufacturing Corp',
  'Manufacturing',
  '🏭',
  'IoT & Analytics',
  '14 months',
  '7 developers',
  $txt$No real-time visibility into supply chain, frequent stockouts and overstock situations, manual demand forecasting causing $3M annually in carrying costs.$txt$,
  $txt$Implemented IoT sensors across warehouses, built real-time tracking dashboard with Angular, deployed ML-based demand forecasting, and automated reorder processes.$txt$,
  $json$[{"metric":"35%","description":"Inventory reduction"},{"metric":"95%","description":"Order fulfillment rate"},{"metric":"$2.5M","description":"Annual savings"},{"metric":"Real-time","description":"Supply chain visibility"}]$json$::jsonb,
  array['Angular','Node.js','AWS IoT','Python','TensorFlow','PostgreSQL','Grafana'],
  6
),
(
  'EdTech Learning Platform',
  'Online Education Startup',
  'Education',
  '🎓',
  'Platform Development',
  '9 months',
  '4 developers',
  $txt$Needed to launch competitive online learning platform from scratch with live classes, course management, and progress tracking to compete with established players.$txt$,
  $txt$Built full-featured LMS with Angular frontend, Node.js backend, integrated video streaming, gamification features, and AI-powered personalized learning paths.$txt$,
  $json$[{"metric":"50K+","description":"Active students"},{"metric":"92%","description":"Course completion rate"},{"metric":"4.9/5","description":"App store rating"},{"metric":"$5M","description":"First-year revenue"}]$json$::jsonb,
  array['Angular','Node.js','MongoDB','AWS','WebRTC','Redis','Stripe'],
  7
),
(
  'Fintech Payment Gateway',
  'Digital Payments Startup',
  'Financial Services',
  '💳',
  'Payment Infrastructure',
  '11 months',
  '6 developers',
  $txt$Needed PCI-DSS compliant payment processing system to handle high transaction volumes with sub-second latency and 99.99% uptime requirements.$txt$,
  $txt$Architected microservices-based payment gateway with .NET Core, implemented distributed caching, built fraud detection ML models, and deployed multi-region on Azure.$txt$,
  $json$[{"metric":"10M+","description":"Monthly transactions"},{"metric":"99.99%","description":"System uptime"},{"metric":"<100ms","description":"Transaction latency"},{"metric":"0.01%","description":"Fraud rate"}]$json$::jsonb,
  array['.NET Core','Angular','Azure','Redis','Kafka','PostgreSQL','ML.NET'],
  8
),
(
  'Restaurant Chain POS System',
  'National Restaurant Group',
  'Hospitality',
  '🍽️',
  'Point of Sale',
  '10 months',
  '5 developers',
  $txt$Outdated POS system causing slow order processing, inventory discrepancies, and no integration with online ordering platforms.$txt$,
  $txt$Built cloud-based POS with real-time inventory sync, integrated with DoorDash/UberEats APIs, and implemented AI-driven demand forecasting.$txt$,
  $json$[{"metric":"40%","description":"Faster order processing"},{"metric":"25%","description":"Reduced food waste"},{"metric":"200+","description":"Locations deployed"},{"metric":"$3M","description":"Annual savings"}]$json$::jsonb,
  array['Angular','Node.js','MongoDB','AWS','Redis','GraphQL','React Native'],
  9
),
(
  'Insurance Claims Automation',
  'Top 10 Insurance Provider',
  'Insurance',
  '📋',
  'Process Automation',
  '12 months',
  '8 developers',
  $txt$Manual claims processing taking 15+ days on average, high error rates, and customer complaints about lack of transparency.$txt$,
  $txt$Implemented AI-powered claims assessment, automated document processing with OCR, and built customer self-service portal with real-time status tracking.$txt$,
  $json$[{"metric":"80%","description":"Faster claims processing"},{"metric":"95%","description":"Accuracy rate"},{"metric":"45%","description":"Cost reduction"},{"metric":"4.7/5","description":"Customer satisfaction"}]$json$::jsonb,
  array['.NET Core','Angular','Azure Cognitive Services','SQL Server','Power Automate','Cosmos DB'],
  10
),
(
  'Smart City Traffic Management',
  'Metropolitan City Government',
  'Government',
  '🚦',
  'IoT Platform',
  '18 months',
  '10 developers',
  $txt$Growing traffic congestion costing the city $50M annually in lost productivity, outdated traffic signal timing, and no real-time monitoring.$txt$,
  $txt$Deployed IoT sensors at 500+ intersections, built AI-driven traffic optimization, and created real-time monitoring dashboard for city operators.$txt$,
  $json$[{"metric":"30%","description":"Reduced congestion"},{"metric":"22%","description":"Lower emissions"},{"metric":"$15M","description":"Annual savings"},{"metric":"500+","description":"Connected intersections"}]$json$::jsonb,
  array['Python','Angular','TensorFlow','AWS IoT','Kafka','PostgreSQL','Grafana'],
  11
),
(
  'Telehealth Platform',
  'Healthcare Startup',
  'Healthcare',
  '👨‍⚕️',
  'Platform Development',
  '8 months',
  '6 developers',
  $txt$COVID-19 pandemic created urgent need for virtual care platform with video consultations, prescription management, and EHR integration.$txt$,
  $txt$Built HIPAA-compliant telehealth platform with WebRTC video, e-prescribing integration, and seamless Epic/Cerner EHR connectivity.$txt$,
  $json$[{"metric":"100K+","description":"Monthly consultations"},{"metric":"4.9/5","description":"Patient rating"},{"metric":"85%","description":"First-visit resolution"},{"metric":"$20M","description":"Series B funding"}]$json$::jsonb,
  array['Angular','Node.js','WebRTC','AWS','HL7 FHIR','PostgreSQL','Twilio'],
  12
),
(
  'Fleet Management System',
  'Logistics Enterprise',
  'Transportation',
  '🚛',
  'IoT & Analytics',
  '14 months',
  '7 developers',
  $txt$No real-time visibility into 2,000+ vehicle fleet, fuel theft issues, and inefficient route planning costing millions annually.$txt$,
  $txt$Implemented GPS tracking with telematics, built AI-powered route optimization, and created predictive maintenance system using vehicle sensor data.$txt$,
  $json$[{"metric":"18%","description":"Fuel savings"},{"metric":"25%","description":"More deliveries/day"},{"metric":"$4M","description":"Annual savings"},{"metric":"40%","description":"Less vehicle downtime"}]$json$::jsonb,
  array['Angular','.NET Core','Azure IoT','ML.NET','SQL Server','SignalR','Power BI'],
  13
),
(
  'Digital Banking Platform',
  'Regional Credit Union',
  'Banking',
  '🏦',
  'Digital Transformation',
  '16 months',
  '9 developers',
  $txt$Legacy core banking system limiting digital capabilities, losing younger customers to fintech competitors, and high operational costs.$txt$,
  $txt$Built modern digital banking platform with mobile-first design, integrated with core banking via APIs, and added features like instant transfers and budgeting tools.$txt$,
  $json$[{"metric":"150%","description":"Mobile adoption increase"},{"metric":"60%","description":"Fewer branch visits"},{"metric":"35K","description":"New accounts"},{"metric":"$2M","description":"Annual savings"}]$json$::jsonb,
  array['Angular','.NET Core','Azure','Plaid','SQL Server','Redis','Ionic'],
  14
),
(
  'HR & Talent Management System',
  'Fortune 100 Corporation',
  'Enterprise',
  '👥',
  'Enterprise Software',
  '20 months',
  '12 developers',
  $txt$Fragmented HR systems across 50+ countries, compliance challenges, and poor employee experience affecting talent retention.$txt$,
  $txt$Built unified global HR platform with localization for 30+ countries, integrated payroll systems, and implemented AI-powered talent matching.$txt$,
  $json$[{"metric":"200K+","description":"Employees onboarded"},{"metric":"50%","description":"Faster hiring"},{"metric":"30%","description":"Better retention"},{"metric":"$10M","description":"Annual savings"}]$json$::jsonb,
  array['Angular','.NET Core','Azure','Workday Integration','SQL Server','Power BI','Azure AD'],
  15
),
(
  'Property Management Platform',
  'Real Estate Investment Trust',
  'Real Estate',
  '🏢',
  'Platform Development',
  '11 months',
  '5 developers',
  $txt$Managing 500+ commercial properties with spreadsheets, tenant communication issues, and no visibility into maintenance requests.$txt$,
  $txt$Built comprehensive property management platform with tenant portal, automated rent collection, and IoT-enabled building management.$txt$,
  $json$[{"metric":"98%","description":"Rent collection rate"},{"metric":"60%","description":"Faster maintenance"},{"metric":"500+","description":"Properties managed"},{"metric":"$5M","description":"Revenue increase"}]$json$::jsonb,
  array['Angular','Node.js','PostgreSQL','AWS','Stripe','SendGrid','IoT sensors'],
  16
),
(
  'Legal Document Automation',
  'Top 50 Law Firm',
  'Legal',
  '⚖️',
  'AI Automation',
  '9 months',
  '4 developers',
  $txt$Associates spending 60% of time on document review, high billing disputes, and inconsistent contract quality across offices.$txt$,
  $txt$Implemented AI-powered contract analysis, built template-based document generation, and created automated billing reconciliation system.$txt$,
  $json$[{"metric":"70%","description":"Less review time"},{"metric":"99%","description":"Contract accuracy"},{"metric":"$8M","description":"Additional billable hours"},{"metric":"40%","description":"Faster turnaround"}]$json$::jsonb,
  array['Python','Angular','Azure OpenAI','Elasticsearch','.NET Core','SQL Server','DocuSign'],
  17
),
(
  'Energy Trading Platform',
  'Energy Trading Firm',
  'Energy',
  '⚡',
  'Trading System',
  '15 months',
  '8 developers',
  $txt$Legacy trading system couldn't handle market volatility, slow execution causing missed opportunities, and regulatory compliance gaps.$txt$,
  $txt$Built high-frequency trading platform with sub-millisecond latency, real-time risk management, and automated regulatory reporting.$txt$,
  $json$[{"metric":"<1ms","description":"Trade execution"},{"metric":"99.999%","description":"System uptime"},{"metric":"35%","description":"Trading volume increase"},{"metric":"$50M","description":"Annual profit increase"}]$json$::jsonb,
  array['.NET Core','Angular','Kafka','Redis','PostgreSQL','TimescaleDB','Kubernetes'],
  18
),
(
  'Pharmaceutical R&D Platform',
  'Biotech Company',
  'Pharmaceutical',
  '💊',
  'Research Platform',
  '18 months',
  '10 developers',
  $txt$Clinical trial data scattered across systems, slow drug discovery process, and difficulty meeting FDA submission requirements.$txt$,
  $txt$Built unified research platform with ML-powered drug candidate screening, automated FDA submission generation, and real-time trial monitoring.$txt$,
  $json$[{"metric":"40%","description":"Faster drug discovery"},{"metric":"100%","description":"FDA compliance"},{"metric":"3","description":"Drugs fast-tracked"},{"metric":"$100M+","description":"R&D savings"}]$json$::jsonb,
  array['Python','Angular','.NET Core','Azure','TensorFlow','PostgreSQL','Databricks'],
  19
),
(
  'Sports Betting Platform',
  'Gaming Startup',
  'Gaming',
  '🎰',
  'Platform Development',
  '12 months',
  '7 developers',
  $txt$Entering competitive sports betting market requiring real-time odds, high concurrency during events, and strict gaming compliance.$txt$,
  $txt$Built scalable betting platform with real-time odds engine, implemented responsible gaming features, and achieved multi-state licensing.$txt$,
  $json$[{"metric":"500K+","description":"Active users"},{"metric":"1M+","description":"Bets per day"},{"metric":"12","description":"States licensed"},{"metric":"$30M","description":"First-year GGR"}]$json$::jsonb,
  array['Node.js','Angular','Redis','Kafka','PostgreSQL','AWS','Terraform'],
  20
),
(
  'Agricultural IoT Platform',
  'AgTech Startup',
  'Agriculture',
  '🌾',
  'IoT Platform',
  '10 months',
  '5 developers',
  $txt$Farmers lacked data-driven insights, water waste in irrigation, and crop yield predictions were unreliable.$txt$,
  $txt$Deployed soil sensors and weather stations, built AI crop management platform, and implemented precision irrigation system.$txt$,
  $json$[{"metric":"30%","description":"Water savings"},{"metric":"25%","description":"Yield increase"},{"metric":"10K+","description":"Acres monitored"},{"metric":"$5M","description":"Farmer savings"}]$json$::jsonb,
  array['Python','Angular','AWS IoT','TensorFlow','PostgreSQL','Grafana','LoRaWAN'],
  21
),
(
  'Airline Operations System',
  'Regional Airline',
  'Aviation',
  '✈️',
  'Operations Platform',
  '14 months',
  '8 developers',
  $txt$Manual crew scheduling, flight disruption management causing delays, and no integrated view of operations.$txt$,
  $txt$Built integrated operations control center with AI crew optimization, real-time disruption management, and predictive maintenance.$txt$,
  $json$[{"metric":"35%","description":"Fewer delays"},{"metric":"$8M","description":"Annual savings"},{"metric":"15%","description":"Better fuel efficiency"},{"metric":"98%","description":"On-time performance"}]$json$::jsonb,
  array['.NET Core','Angular','Azure','ML.NET','SQL Server','SignalR','Power BI'],
  22
),
(
  'Subscription Box Platform',
  'D2C E-commerce Brand',
  'E-Commerce',
  '📦',
  'E-Commerce Platform',
  '7 months',
  '4 developers',
  $txt$High customer acquisition costs, poor retention rates, and fulfillment errors causing customer complaints.$txt$,
  $txt$Built personalized subscription platform with AI product recommendations, automated fulfillment integration, and customer engagement tools.$txt$,
  $json$[{"metric":"45%","description":"Better retention"},{"metric":"30%","description":"Higher AOV"},{"metric":"200K","description":"Subscribers"},{"metric":"99.5%","description":"Fulfillment accuracy"}]$json$::jsonb,
  array['Angular','Node.js','MongoDB','Stripe','ShipStation','Klaviyo','AWS'],
  23
),
(
  'Construction Project Management',
  'General Contractor',
  'Construction',
  '🏗️',
  'Project Management',
  '11 months',
  '6 developers',
  $txt$Projects consistently over budget, poor subcontractor coordination, and no real-time visibility into project status.$txt$,
  $txt$Built construction management platform with BIM integration, automated progress tracking using drone imagery, and predictive cost management.$txt$,
  $json$[{"metric":"20%","description":"Under budget"},{"metric":"30%","description":"Faster completion"},{"metric":"$50M+","description":"Projects managed"},{"metric":"Zero","description":"Safety incidents"}]$json$::jsonb,
  array['Angular','.NET Core','Azure','Autodesk APIs','Computer Vision','PostgreSQL','Power BI'],
  24
),
(
  'Nonprofit Donor Management',
  'National Charity Organization',
  'Nonprofit',
  '❤️',
  'CRM Platform',
  '8 months',
  '4 developers',
  $txt$Disconnected donor data, ineffective fundraising campaigns, and high administrative overhead limiting program spending.$txt$,
  $txt$Built unified donor platform with AI-powered giving predictions, automated campaign management, and integrated volunteer coordination.$txt$,
  $json$[{"metric":"50%","description":"More donations"},{"metric":"35%","description":"Lower admin costs"},{"metric":"2M+","description":"Donors managed"},{"metric":"85%","description":"Donor retention"}]$json$::jsonb,
  array['Angular','Node.js','Salesforce NPSP','AWS','Stripe','Mailchimp','PostgreSQL'],
  25
),
(
  'Gym & Fitness Platform',
  'Fitness Franchise',
  'Fitness',
  '💪',
  'Member Platform',
  '9 months',
  '5 developers',
  $txt$Member engagement dropping, no virtual class offerings, and each franchise location operating on different systems.$txt$,
  $txt$Built unified fitness platform with on-demand classes, wearable integration, and franchise-wide member management.$txt$,
  $json$[{"metric":"60%","description":"Member engagement up"},{"metric":"300+","description":"Locations unified"},{"metric":"40%","description":"Revenue increase"},{"metric":"4.8/5","description":"App store rating"}]$json$::jsonb,
  array['Angular','Node.js','AWS','React Native','Stripe','MongoDB','Wearable SDKs'],
  26
),
(
  'Hotel Revenue Management',
  'Boutique Hotel Chain',
  'Hospitality',
  '🏨',
  'Revenue Optimization',
  '10 months',
  '5 developers',
  $txt$Static pricing losing revenue, no competitive rate intelligence, and poor demand forecasting leading to empty rooms.$txt$,
  $txt$Built dynamic pricing engine with ML demand forecasting, competitor rate monitoring, and automated channel management.$txt$,
  $json$[{"metric":"25%","description":"RevPAR increase"},{"metric":"15%","description":"Higher occupancy"},{"metric":"$3M","description":"Additional revenue"},{"metric":"Real-time","description":"Rate optimization"}]$json$::jsonb,
  array['Python','Angular','.NET Core','Azure ML','PostgreSQL','Redis','OTA APIs'],
  27
),
(
  'Media Streaming Platform',
  'Sports Media Company',
  'Media',
  '📺',
  'Streaming Platform',
  '14 months',
  '9 developers',
  $txt$Needed to launch direct-to-consumer streaming service to compete with major platforms while maintaining broadcast quality.$txt$,
  $txt$Built scalable OTT platform with adaptive bitrate streaming, personalized content recommendations, and multi-device support.$txt$,
  $json$[{"metric":"2M+","description":"Subscribers"},{"metric":"99.9%","description":"Stream uptime"},{"metric":"4K HDR","description":"Quality delivered"},{"metric":"$50M","description":"Annual revenue"}]$json$::jsonb,
  array['Angular','Node.js','AWS MediaServices','CDN','MongoDB','Redis','Roku/Apple TV SDKs'],
  28
),
(
  'Warehouse Automation System',
  '3PL Provider',
  'Logistics',
  '📦',
  'Automation',
  '16 months',
  '8 developers',
  $txt$Manual picking processes causing errors, slow order fulfillment, and difficulty scaling during peak seasons.$txt$,
  $txt$Implemented automated picking with robotics, built WMS with real-time inventory, and deployed predictive demand planning.$txt$,
  $json$[{"metric":"300%","description":"Throughput increase"},{"metric":"99.9%","description":"Picking accuracy"},{"metric":"50%","description":"Labor cost reduction"},{"metric":"Same-day","description":"Shipping capability"}]$json$::jsonb,
  array['Python','Angular','.NET Core','ROS','AWS','PostgreSQL','Computer Vision'],
  29
),
(
  'Veterinary Practice Management',
  'Vet Clinic Chain',
  'Veterinary',
  '🐾',
  'Practice Management',
  '8 months',
  '4 developers',
  $txt$Paper-based records, double-booked appointments, and no integrated pharmacy or lab management.$txt$,
  $txt$Built cloud-based practice management with electronic records, online booking, integrated pharmacy, and client communication portal.$txt$,
  $json$[{"metric":"40%","description":"More appointments"},{"metric":"Zero","description":"Double bookings"},{"metric":"35%","description":"Revenue increase"},{"metric":"4.9/5","description":"Client satisfaction"}]$json$::jsonb,
  array['Angular','Node.js','MongoDB','AWS','Twilio','Stripe','Lab integrations'],
  30
),
(
  'Electric Vehicle Charging Network',
  'EV Infrastructure Company',
  'Energy',
  '🔌',
  'IoT Platform',
  '12 months',
  '7 developers',
  $txt$Managing 5,000+ charging stations, real-time availability updates needed, and complex billing for different rate structures.$txt$,
  $txt$Built charging network platform with real-time station monitoring, mobile app for drivers, and flexible billing engine.$txt$,
  $json$[{"metric":"5K+","description":"Stations managed"},{"metric":"99.5%","description":"Station uptime"},{"metric":"1M+","description":"Charging sessions/month"},{"metric":"Real-time","description":"Availability updates"}]$json$::jsonb,
  array['Angular','Node.js','OCPP','AWS IoT','PostgreSQL','Redis','React Native'],
  31
),
(
  'Fashion E-commerce Personalization',
  'Online Fashion Retailer',
  'Retail',
  '👗',
  'AI Personalization',
  '9 months',
  '5 developers',
  $txt$Low conversion rates, high return rates due to sizing issues, and generic product recommendations.$txt$,
  $txt$Implemented AI-powered virtual try-on, size recommendation engine, and personalized product discovery using computer vision.$txt$,
  $json$[{"metric":"45%","description":"Conversion increase"},{"metric":"35%","description":"Fewer returns"},{"metric":"60%","description":"Higher engagement"},{"metric":"$15M","description":"Additional revenue"}]$json$::jsonb,
  array['Python','Angular','TensorFlow','AWS','Computer Vision','PostgreSQL','Redis'],
  32
),
(
  'Museum Digital Experience',
  'National Museum',
  'Arts & Culture',
  '🏛️',
  'Digital Experience',
  '10 months',
  '5 developers',
  $txt$Declining visitor engagement, no digital presence for collections, and missed revenue opportunities from virtual visitors.$txt$,
  $txt$Built immersive digital platform with virtual tours, AR exhibit enhancement, online ticketing, and educational content portal.$txt$,
  $json$[{"metric":"500K+","description":"Virtual visitors"},{"metric":"45%","description":"More engagement"},{"metric":"$2M","description":"Digital revenue"},{"metric":"Global","description":"Audience reach"}]$json$::jsonb,
  array['Angular','Three.js','AR.js','Node.js','AWS','MongoDB','Stripe'],
  33
),
(
  'Insurance Underwriting AI',
  'Commercial Insurance Provider',
  'Insurance',
  '📊',
  'AI Platform',
  '14 months',
  '8 developers',
  $txt$Manual underwriting taking weeks, inconsistent risk assessment, and losing deals to faster competitors.$txt$,
  $txt$Built AI-powered underwriting platform with automated risk scoring, document analysis, and instant quote generation.$txt$,
  $json$[{"metric":"Minutes","description":"vs weeks for quotes"},{"metric":"30%","description":"Better loss ratios"},{"metric":"3x","description":"Quote volume"},{"metric":"$20M","description":"New premium"}]$json$::jsonb,
  array['.NET Core','Angular','Azure ML','Cosmos DB','Azure Cognitive Services','Power BI'],
  34
),
(
  'Concert Ticketing Platform',
  'Live Events Company',
  'Entertainment',
  '🎵',
  'E-Commerce',
  '8 months',
  '6 developers',
  $txt$Bot scalping causing customer frustration, payment failures during high-demand sales, and no secondary market control.$txt$,
  $txt$Built anti-bot ticketing platform with queue management, blockchain-verified tickets, and controlled resale marketplace.$txt$,
  $json$[{"metric":"95%","description":"Bot prevention"},{"metric":"Zero","description":"Payment failures"},{"metric":"5M+","description":"Tickets sold"},{"metric":"50%","description":"Scalping reduction"}]$json$::jsonb,
  array['Angular','Node.js','AWS','Redis','PostgreSQL','Blockchain','Stripe'],
  35
),
(
  'Clinical Laboratory System',
  'Diagnostic Lab Network',
  'Healthcare',
  '🔬',
  'LIS/LIMS',
  '15 months',
  '8 developers',
  $txt$Paper-based workflows, manual result entry causing errors, and slow turnaround times affecting patient care.$txt$,
  $txt$Built modern LIS with automated instrument integration, real-time result delivery, and patient portal access.$txt$,
  $json$[{"metric":"70%","description":"Faster turnaround"},{"metric":"99.9%","description":"Result accuracy"},{"metric":"10M+","description":"Tests/year processed"},{"metric":"Zero","description":"Critical result delays"}]$json$::jsonb,
  array['.NET Core','Angular','HL7','SQL Server','Azure','ASTM','Power BI'],
  36
),
(
  'Renewable Energy Trading',
  'Clean Energy Developer',
  'Energy',
  '🌱',
  'Trading Platform',
  '11 months',
  '6 developers',
  $txt$Complex REC trading requirements, manual tracking of renewable credits, and regulatory reporting burden.$txt$,
  $txt$Built renewable energy certificate trading platform with automated tracking, market integration, and compliance reporting.$txt$,
  $json$[{"metric":"$100M+","description":"Credits traded"},{"metric":"100%","description":"Compliance rate"},{"metric":"80%","description":"Less admin time"},{"metric":"Real-time","description":"Market access"}]$json$::jsonb,
  array['Angular','.NET Core','Azure','PostgreSQL','Blockchain','Power BI','RESTful APIs'],
  37
);

-- Portfolio testimonial (single client quote near top of page)
delete from testimonials where context = 'portfolio';
insert into testimonials (context, quote, author_name, author_title, company, sort_order) values
(
  'portfolio',
  $txt$Working with Nexa Web Service was a game-changer for our business. They transformed our legacy systems into a modern, scalable platform that reduced our operational costs by 40% and improved customer satisfaction scores dramatically.$txt$,
  'Representative Client Feedback',
  'Enterprise Digital Transformation Project',
  null,
  1
);
