-- Seed: per-route SEO metadata, replacing the static `data` blocks that used
-- to live in app.routes.ts. Note: the original source had mojibake ("â€\"")
-- from a broken em-dash encoding — corrected to a real em-dash (—) here.

truncate table page_seo restart identity cascade;

insert into page_seo (slug, title, description, keywords, og_image_url) values
('', $txt$Nexa Web Service — Software Solutions | Digital Transformation & Development$txt$, $txt$Nexa Web Service delivers custom digital transformation solutions and enterprise software. 8+ years specializing in Angular, React, .NET Core, Azure DevOps, and Healthcare SaaS — for US and international clients.$txt$, 'software engineer USA, digital transformation, full-stack developer, custom development, enterprise solutions', 'https://nexawebservice.com/assets/og-image.jpg'),
('about', $txt$About Nexa Web Service — Software Solutions Team$txt$, $txt$Kamran Sohail — Senior Full Stack Developer with 8+ years building Angular, React, .NET Core, and Azure DevOps solutions for US, UAE, and UK clients. Founder of Nexa Web Service.$txt$, 'about software engineer, technical consultant, digital transformation expert, software development', 'https://nexawebservice.com/assets/og-image.jpg'),
('services', 'Services - Digital Transformation, Cloud Migration & Custom Development | USA', $txt$Professional software development services including digital transformation, custom development, cloud migration, legacy modernization, and technical consulting.$txt$, 'software development services, digital transformation, cloud migration, legacy modernization, custom development, technical consulting', 'https://nexawebservice.com/assets/services-og-image.jpg'),
('portfolio', 'Portfolio - Case Studies & Completed Projects | Software Solutions', $txt$Explore 50+ completed projects showcasing expertise in digital transformation, cloud migration, custom development, and enterprise solutions.$txt$, 'portfolio, case studies, completed projects, software solutions, enterprise development, project examples', 'https://nexawebservice.com/assets/portfolio-og-image.jpg'),
('blog', 'Blog - Technical Insights & Software Development Articles | USA', $txt$Read technical articles and insights on digital transformation, software engineering best practices, cloud architecture, and industry trends.$txt$, 'software engineering blog, technical articles, digital transformation, cloud architecture, development best practices', 'https://nexawebservice.com/assets/blog-og-image.jpg'),
('contact', 'Contact - Schedule Your Free Consultation | Software Solutions', $txt$Get in touch to schedule a free 30-minute strategy session. Discuss your project needs with an experienced technical consultant.$txt$, 'contact, consultation, schedule meeting, software engineer contact, technical consultation, free consultation', 'https://nexawebservice.com/assets/contact-og-image.jpg'),
('courses', 'Web Development Courses | Learn HTML, CSS, JavaScript, Angular, React | USA', $txt$Comprehensive web development courses from beginner to advanced. Master HTML, CSS, Bootstrap, JavaScript, jQuery, Angular, React, and Full Stack Development.$txt$, 'web development courses, learn coding, JavaScript courses, Angular courses, React courses, Bootstrap courses, jQuery, HTML CSS', 'https://nexawebservice.com/assets/courses-og-image.jpg'),
('pricing', $txt$Pricing — Web Development & Academy Courses | Nexa Web Service$txt$, $txt$Transparent pricing for web development projects starting at $500. Academy courses from $39. US clients welcome. Pay via PayPal or Wise.$txt$, 'web development pricing, freelance developer rates, website cost, course pricing, affordable web development', 'https://nexawebservice.com/assets/og-image.jpg'),
('faq', $txt$FAQ — Working with International Clients | Nexa Web Service$txt$, $txt$Answers to common questions about working with Nexa Web Service from the US, payment methods, project timelines, and our Academy courses.$txt$, 'faq, international clients, USD payments, remote developer, web development questions, timezone', 'https://nexawebservice.com/assets/og-image.jpg');
